package game;

public enum Names {
    Creaturescale,
    Snakey,
    Assassin,
    Cloudy,
    Miss_You,
    Candy_Clay,
    Creep,
    Shipman,
    Rapid_Power,
    Fission_Isolate,
    War_Dot_Com,
    Board_Topper,
    Count_Swagula,
    Fission_Razor,
    Combat_Nomad,
    Electric_Tune,
    Wellendowed,
    Penguin,
    Necromancer,
    Dorathedestroyer,
    Masters_Only,
    Lftfeet,
    Smoke_Zone,
    Battalion,
    Bikers_Joker,
    Pocket_Moon_Juice,
    Game_X_Change,
    Fire_Bullet,
    Mojo_Union,
    Carry_No_Bliss,

}
